version: '3.2'

services:
  web:
    container_name: ${APP_NAME}_web
    build:
      context: ./docker/web
    ports:
      - 8950:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - php
 
  db:
    image: mysql:5.7
    restart: always
    env_file:
      ./.env
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
    expose:
      - '3306'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']


  php:
    build:
        context: .
        dockerfile: docker/web/php.dockerfile
    ports:
        - 9000:9000
    depends_on:
        - db
    volumes:
        - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - UPLOAD_LIMIT=3000000000